<script setup lang="ts">
import {
  MousePointer2,
  Square,
  Circle,
  Diamond,
  ArrowUpRight,
  Minus,
  Pencil,
  Type,
  Eraser,
  Hand,
  Image,
  Undo2,
  Redo2,
  Plus,
  Grid3X3,
  Sun,
  Moon,
  Share2,
  Download,
  Menu,
  Trash2,
  X,
  HelpCircle,
  Crosshair,
  Users,
  Zap,
  Link,
  Copy,
  Check,
  Keyboard,
  MoreHorizontal,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  GripHorizontal,
  Folder,
  FolderPlus,
  CreditCard,
  LogIn,
  LogOut,
  Cloud,
  CloudOff,
  Save,
  FolderOpen,
  Crown,
  Sparkles,
  Star,
  PanelLeft,
  ArrowUpToLine,
  ArrowDownToLine,
  Layers,
  Clock,
  File,
  Archive,
  Tag,
  ArrowDownUp,
  ArrowUpDown,
  List,
  Home,
  Search,
} from 'lucide-vue-next'
import { computed } from 'vue'

const props = defineProps<{
  name: string
}>()

const iconMap: Record<string, any> = {
  cursor: MousePointer2,
  rectangle: Square,
  ellipse: Circle,
  diamond: Diamond,
  arrow: ArrowUpRight,
  line: Minus,
  pencil: Pencil,
  text: Type,
  eraser: Eraser,
  hand: Hand,
  image: Image,
  undo: Undo2,
  redo: Redo2,
  plus: Plus,
  minus: Minus,
  grid: Grid3X3,
  sun: Sun,
  moon: Moon,
  share: Share2,
  download: Download,
  menu: Menu,
  trash: Trash2,
  close: X,
  snap: Crosshair,
  users: Users,
  zap: Zap,
  link: Link,
  copy: Copy,
  check: Check,
  keyboard: Keyboard,
  more: MoreHorizontal,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  grip: GripHorizontal,
  folder: Folder,
  folderOpen: FolderOpen,
  folderPlus: FolderPlus,
  creditCard: CreditCard,
  logIn: LogIn,
  logOut: LogOut,
  cloud: Cloud,
  cloudOff: CloudOff,
  save: Save,
  crown: Crown,
  sparkles: Sparkles,
  star: Star,
  starFilled: Star, // Same icon, can be styled differently
  panelLeft: PanelLeft,
  bringToFront: ArrowUpToLine,
  sendToBack: ArrowDownToLine,
  bringForward: ChevronUp,
  sendBackward: ChevronDown,
  layers: Layers,
  clock: Clock,
  file: File,
  archive: Archive,
  tag: Tag,
  sortAsc: ArrowUpDown,
  sortDesc: ArrowDownUp,
  list: List,
  home: Home,
  search: Search,
}

const IconComponent = computed(() => iconMap[props.name] || HelpCircle)
</script>

<template>
  <component :is="IconComponent" :size="16" />
</template>
